# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 355)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("QWidget{\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
" background-color:rgb(125, 125, 125);  \n"
" border-style:inset;\n"
"padding-left:3px;\n"
"padding-top:3px; \n"
"}\n"
"\n"
"QPushButton#pushButton_3{\n"
"background-color: rgb(255, 255, 127);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 12pt \"微软雅黑\";\n"
"border:1px solid red;\n"
"border-radius:5px;\n"
"}\n"
"QLabel#label_2{\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"微软雅黑\";\n"
"}\n"
"QLabel#label{\n"
"background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 0, 0);\n"
"font: 75 12pt \"微软雅黑\";\n"
"}\n"
"\n"
"QGroupBox\n"
"{\n"
"border: 2px solid red;\n"
"border-radius:5px;\n"
"margin-top:2ex;\n"
"font-family:楷体;\n"
"font:bold 28px;\n"
" \n"
"}\n"
"QGroupBox::title\n"
"{\n"
"subcontrol-origin:margin;\n"
"subcontrol-position:top center;\n"
"padding:0 3px;\n"
"font: 75 12pt \"微软雅黑\";\n"
"color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton#pushButton{\n"
"background-color: rgb(0, 170, 0);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton_2{\n"
"background-color: rgb(255, 85, 0);\n"
"border-radius:5px;\n"
"}\n"
"QMessageBox{\n"
"background-color: #f1f1f1;\n"
"}\n"
"QMessageBox>QLabel{\n"
"color:black;\n"
"background-color: #f1f1f1;\n"
"}\n"
"QMessageBox QPushButton{ \n"
"    background-color:#bebebe;  \n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 431, 261))
        self.groupBox.setMinimumSize(QtCore.QSize(431, 261))
        self.groupBox.setMaximumSize(QtCore.QSize(431, 261))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 411, 221))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 312, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 310, 91, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 5, 181, 31))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "动态壁纸设置工具"))
        self.groupBox.setTitle(_translate("MainWindow", "预览"))
        self.label_2.setText(_translate("MainWindow", "等待视频......"))
        self.pushButton.setText(_translate("MainWindow", "运用"))
        self.pushButton_2.setText(_translate("MainWindow", "取消壁纸"))
        self.pushButton_3.setText(_translate("MainWindow", "运用"))
        self.label.setText(_translate("MainWindow", "Ctrl+Q 退出"))
